/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('vexip-ui')['Breadcrumb']
    BreadcrumbItem: typeof import('vexip-ui')['BreadcrumbItem']
    Button: typeof import('vexip-ui')['Button']
    Card: typeof import('vexip-ui')['Card']
    ConfigProvider: typeof import('vexip-ui')['ConfigProvider']
    FormItem: typeof import('vexip-ui')['FormItem']
    FormReset: typeof import('vexip-ui')['FormReset']
    FormSubmit: typeof import('vexip-ui')['FormSubmit']
    Input: typeof import('vexip-ui')['Input']
    Layout: typeof import('vexip-ui')['Layout']
    Linker: typeof import('vexip-ui')['Linker']
    Menu: typeof import('vexip-ui')['Menu']
    MenuItem: typeof import('vexip-ui')['MenuItem']
    Modal: typeof import('vexip-ui')['Modal']
    NumberInput: typeof import('vexip-ui')['NumberInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('vexip-ui')['Row']
    ScrollX: typeof import('./../src/components/ScrollX.vue')['default']
    Select: typeof import('vexip-ui')['Select']
    Space: typeof import('vexip-ui')['Space']
    Switch: typeof import('vexip-ui')['Switch']
    Table: typeof import('vexip-ui')['Table']
    TableColumn: typeof import('vexip-ui')['TableColumn']
    Tag: typeof import('vexip-ui')['Tag']
    TheIcon: typeof import('./../src/components/TheIcon.vue')['default']
  }
}
