version: '2.4'

services:
  server:
    build :
      context: ./
      dockerfile: Dockerfile
    restart: always
    platform: linux/arm64/v8
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql/mysql-server:latest
    container_name: nest-mysql
    env_file:
      - .env
      - .env.prod
    environment:
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #设置utf
    volumes:
      - mysql:/data
    platform: linux/arm64/v8
    restart: always
  redis:
    image: redis
    restart: always
    env_file:
      - .env
      - .env.prod
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    platform: linux/arm64/v8

volumes:
  mysql:
  redis: