version: '3'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: nest-mysql
    restarts: always
    env_file:
      - .env
      - .env.prod
    ports:
      -"3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #设置utf8字符集