// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('vexip-ui')['Button']
    Checkbox: typeof import('vexip-ui')['Checkbox']
    Form: typeof import('vexip-ui')['Form']
    FormItem: typeof import('vexip-ui')['FormItem']
    FormReset: typeof import('vexip-ui')['FormReset']
    FormSubmit: typeof import('vexip-ui')['FormSubmit']
    Icon: typeof import('vexip-ui')['Icon']
    Input: typeof import('vexip-ui')['Input']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('vexip-ui')['Switch']
  }
}
