// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('vexip-ui')['Breadcrumb']
    BreadcrumbItem: typeof import('vexip-ui')['BreadcrumbItem']
    Button: typeof import('vexip-ui')['Button']
    Card: typeof import('vexip-ui')['Card']
    Checkbox: typeof import('vexip-ui')['Checkbox']
    DatePicker: typeof import('vexip-ui')['DatePicker']
    Form: typeof import('vexip-ui')['Form']
    FormItem: typeof import('vexip-ui')['FormItem']
    FormReset: typeof import('vexip-ui')['FormReset']
    FormSubmit: typeof import('vexip-ui')['FormSubmit']
    Icon: typeof import('vexip-ui')['Icon']
    Input: typeof import('vexip-ui')['Input']
    Layout: typeof import('vexip-ui')['Layout']
    Linker: typeof import('vexip-ui')['Linker']
    Menu: typeof import('vexip-ui')['Menu']
    MenuItem: typeof import('vexip-ui')['MenuItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('vexip-ui')['Row']
    ScrollX: typeof import('./../components/ScrollX.vue')['default']
    Select: typeof import('vexip-ui')['Select']
    Space: typeof import('vexip-ui')['Space']
    Table: typeof import('vexip-ui')['Table']
    TableColumn: typeof import('vexip-ui')['TableColumn']
    Tag: typeof import('vexip-ui')['Tag']
    TheIcon: typeof import('./../components/TheIcon.vue')['default']
  }
}
